language: php

php:
  - '7.1'
  - '7.2'
  #- '7.3'
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

branches:
  only:
    - master
    - /^v\d+\.\d+$/

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - composer run-script --timeout=0 test

notifications:
  email:
    on_success: never
