language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

#branches:
#  only:
#    - master
#    - rc

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --verbose
